name: 'elastic_dbt_interview'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  elastic_dbt_interview:
    +database: dbt
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +schema: marts
      +materialized: table
    reporting:
      +schema: reporting
      +materialized: table
    staging:
      +schema: staging
      +materialized: view

vars:
  "dbt_date:time_zone": "Europe/Berlin"
  "query_opportunity_stage": "select distinct stage_name_underscored from staging.stg_salesforce__opportunity order by stage_sort_order asc"
  "query_case_priority": "select distinct lower(priority) from staging.stg_salesforce__case order by priority_order asc"
  "query_case_type": "select distinct lower(type) from staging.stg_salesforce__case"
